---
title: "Visualise madingley outputs and indicators"
author: "Simone Stevenson"
date: "27/08/2021"
output: html_document
---

```{r setup, include=FALSE}
# Load package libraries

## Data wrangling
library(tidyverse)

## Plotting
library(ggplot2)
library(cowplot)
library(plotly)

species_abundance_plots <- readRDS("N:\\Quantitative-Ecology\\Indicators-Project\\Serengeti\\Outputs_from_indicator_code\\Indicator_plots\\2021-08-30_species_abundance_plots.rds")

```

# Baseline Scenario

```{r baseline, fig.width=15, fig.height=10}
par(mfrow=c(2,3))

baseline <- species_abundance_plots[[1]]

line1 <- plot_grid(species_abundance_plots[[1]][[1]],
                   species_abundance_plots[[1]][[2]],
                   ncol = 2, align = "hv")

line1

line2 <- plot_grid(species_abundance_plots[[1]][[3]],
                   species_abundance_plots[[1]][[4]],
                   ncol = 2, align = "v")

line2

line3 <- plot_grid(species_abundance_plots[[1]][[5]],
                   species_abundance_plots[[1]][[6]],
                   ncol = 2, align = "v")

line3

```
# Land use Scenario

```{r land use, fig.width=15, fig.height=10}
par(mfrow=c(2,3))


line1 <- plot_grid(species_abundance_plots[[2]][[1]],
                   species_abundance_plots[[2]][[2]],
                   ncol = 2, align = "hv")

line1

line2 <- plot_grid(species_abundance_plots[[2]][[3]],
                   species_abundance_plots[[2]][[4]],
                   ncol = 2, align = "v")

line2

line3 <- plot_grid(species_abundance_plots[[2]][[5]],
                   species_abundance_plots[[2]][[6]],
                   ncol = 2, align = "v")

line3

```

# Carnivore Harvesting Scenario

```{r carnivores, fig.width=15, fig.height=10}
par(mfrow=c(2,3))

i <- 3

line1 <- plot_grid(species_abundance_plots[[i]][[1]],
                   species_abundance_plots[[i]][[2]],
                   ncol = 2, align = "hv")

line1

line2 <- plot_grid(species_abundance_plots[[i]][[3]],
                   species_abundance_plots[[i]][[4]],
                   ncol = 2, align = "v")

line2

line3 <- plot_grid(species_abundance_plots[[i]][[5]],
                   species_abundance_plots[[i]][[6]],
                   ncol = 2, align = "v")

line3

```

# Herbivore Harvesting Scenario

```{r herbivores, fig.width=15, fig.height=10}
par(mfrow=c(2,3))

i <- 4

line1 <- plot_grid(species_abundance_plots[[i]][[1]],
                   species_abundance_plots[[i]][[2]],
                   ncol = 2, align = "hv")

line1

line2 <- plot_grid(species_abundance_plots[[i]][[3]],
                   species_abundance_plots[[i]][[4]],
                   ncol = 2, align = "v")

line2

line3 <- plot_grid(species_abundance_plots[[i]][[5]],
                   species_abundance_plots[[i]][[6]],
                   ncol = 2, align = "v")

line3

```