---
title: "Visualising different data smoothing options for the RLI"
author: "Simone Stevenson"
date: "08/09/2021"
output:
  pdf_document: default
  html_document: default
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set( echo=FALSE,results='hide',fig.keep='all', message = FALSE,
  warnings = FALSE, comment = '', fig.width = 6, fig.height = 6
)
```

```{r load libraries}

rm(list = ls())

## Data wrangling

library(tidyverse)
library(rlist)
library(zoo)

## Data visualisation
library(ggplot2)
library(viridisLite)
library(ggridges)
library(cowplot)
library(ggThemeAssist)
library(scales)


```

```{r template chunk}

```

```{r ggplot theme}

plot_theme <- theme(panel.background = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              legend.position = "bottom",
              legend.key.size = unit(0.25, 'cm'),
              plot.title = element_text(size = 10, face = "bold"),
              legend.title=element_text(size=6), 
              legend.text=element_text(size=5),
              axis.line = element_line(colour = "black"),
              axis.title.x = element_text(size=8),
              axis.title.y = element_text(size=8),
              axis.text.x = element_text(size=8),
              axis.text.y = element_text(size=8),
              axis.ticks.x = element_blank(), 
              axis.ticks.y = element_blank())

```

```{r colour palettes}

show_col(viridis_pal()(20))
show_col(viridis_pal(option = "plasma")(20))
show_col(viridis_pal(option = "magma")(20))
show_col(viridis_pal(option = "inferno")(20))
show_col(viridis_pal(option = "mako")(20))
show_col(viridis_pal(option = "cividis")(20))
show_col(viridis_pal(option = "rocket")(20))
show_col(viridis_pal(option = "turbo")(20))

```

# Prep data

```{r load inputs and data}

location <- 'Serengeti'

indicators_project <- "N:/Quantitative-Ecology/Indicators-Project"

# Analysis inputs are the outputs of 2_calculate_madingley_indicators.R

analysis_inputs <- "N:/Quantitative-Ecology/Indicators-Project/Serengeti/Outputs_from_indicator_code/Indicator_outputs/general/"

# Inputs ----

# Specify the date of inputs you want to use

input_date <- "2021-09-27"

# Get date to label outputs

output_date <- Sys.Date() 

scenarios_title <- list("Baseline", "Land use", 
                  "Carnivore harvesting", 
                  "Herbivore harvesting")

# Scenario we want to plot

plot_scenario <- "000_Baseline"

plot_species <- "10.45"

# Set up output folders

manuscript_plots_folder <- file.path(indicators_project, 
                                     "/Serengeti/Outputs_from_analysis_code/manuscript_plots_folder",
                                   output_date)

if( !dir.exists( file.path(manuscript_plots_folder) ) ) {
  dir.create( file.path(manuscript_plots_folder), recursive = TRUE )
  
}

supporting_info_plots_folder <- file.path(indicators_project, 
                                     "/Serengeti/Outputs_from_analysis_code/supporting_info_plots_folder",
                                   output_date)

if( !dir.exists( file.path(supporting_info_plots_folder) ) ) {
  dir.create( file.path(supporting_info_plots_folder), recursive = TRUE )
  
}

```

```{r load data}

# Load data
scenario_ab_gl_formatted <- readRDS(file.path(analysis_inputs, input_date,
                                       "formatted_abundance_1.rds"))

scenario_decomposed <- readRDS(file.path(analysis_inputs, input_date,
                                       "decomposed_abundance_2.rds"))

scenario_averaged <- readRDS(file.path(analysis_inputs, input_date,
                                       "averaged_abundance_3.rds"))

scenario_filtered <- readRDS(file.path(analysis_inputs, input_date,
                                       "weird_groups_removed_abundance_4.rds"))

scenario_smoothed_abundance <- readRDS(file.path(analysis_inputs, input_date,
                                       "smoothed_abundance_5.rds"))

scenario_harvested <- readRDS(file.path(analysis_inputs, input_date))

scenario_smoothed_5_reps <- readRDS(file.path(analysis_inputs, input_date ))

scenarios <- c("Baseline", "Land use", "Harvesting carnivores", "Harvesting herbivores")

```
# Plots of raw abundance

```{r raw abundance plots}

raw_abundance_single <- scenario_ab_gl_formatted[[1]]

raw_plot_inputs <- raw_abundance_single[1:4] 

plots <- list()
lims <- list()

for (i in seq_along(raw_plot_inputs)) {
  
data <- raw_plot_inputs[[i]] %>% 
          filter(group_id == plot_species) %>% 
          arrange(monthly_time_step) %>%                         
          slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
          mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
                 filter(annual_time_step > 0) %>% 
          arrange(monthly_time_step) %>% 
          group_by(annual_time_step) %>% 
          filter(abundance == first(na.omit(abundance))) %>% 
          filter(annual_time_step > 190 & annual_time_step < 211) %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))

if (i  == 2) {
    
 data$abundance[6] <- 0
 
 data$abundance[18] <- 0
 
 data <-  data %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
 
}

 if(i == 3) {
   
 data$abundance[1:10] <- 0
 
 #data$abundance[18] <- 0
 
 data <-  data %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
   
 }

if(i == 4) {
  
  lims[[i]] <- cbind(min(data$abundance, na.rm = TRUE), 
                     max(data$abundance, na.rm = TRUE))
  
 data <-  data %>% 
          mutate(false_extinction = ifelse(abundance == 0, TRUE,
                                    ifelse(abundance > 0, FALSE,
                                                     NA)))
  
 plots[[i]] <- ggplot() +
               plot_theme +
               geom_line(data = data, aes(annual_time_step, abundance), col = "white") +
               geom_point(data = data, aes(annual_time_step, abundance,
                                                fill = false_extinction),
                           shape = 21, size = 3, col = "white") +
  scale_fill_manual(values=c('white', 'white')) +
                #coord_cartesian(ylim = c(0,45)) +
                labs(x = "Time",
                     y = "Abundance",
                     title = paste("Replicate", i, sep = " "))+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))+
  guides(fill = guide_legend(override.aes = list(alpha=1)))

  } else {
  
  lims[[i]] <- cbind(min(data$abundance, na.rm = TRUE), 
                     max(data$abundance, na.rm = TRUE))

  plots[[i]] <- ggplot() +
                geom_line(data = data, aes(annual_time_step, abundance)) +
                geom_point(data = data, aes(annual_time_step, abundance,
                                                fill = false_extinction),
                           shape = 21, size = 3) +
  scale_fill_manual(values=c('white', 'red')) +
                plot_theme +
                #coord_cartesian(ylim = c(0,45)) +
                labs(x = "Time",
                     y = "Abundance",
                     title = paste("Replicate", i, sep = " "))+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))

  }
}

abundance_plot <- plot_grid(plots[[1]],
                            plots[[2]],
                            plots[[3]],
                             plots[[4]],
                            ncol = 4, align = "v")

abundance_plot

ggsave(file.path(supporting_info_plots_folder, "0_no_lions.png"),
       width = 20,
       height = 8,
       units = "cm",
       abundance_plot)

lims1 <- do.call(rbind, lims) 

plotlims <- c(min(lims1[,1], na.rm = TRUE),
          max(lims1[,2], na.rm = TRUE))
        

```

# Plots of raw abundance

```{r raw abundance plots}

raw_abundance_single <- scenario_ab_gl_formatted[[1]]

raw_plot_inputs <- raw_abundance_single[1:3] 

plots <- list()
lims <- list()

for (i in seq_along(raw_plot_inputs)) {
  
data <- raw_plot_inputs[[i]] %>% 
          filter(group_id == plot_species) %>% 
          arrange(monthly_time_step) %>%                         
          slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
          mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
                 filter(annual_time_step > 0) %>% 
          arrange(monthly_time_step) %>% 
          group_by(annual_time_step) %>% 
          filter(abundance == first(na.omit(abundance))) %>% 
          filter(annual_time_step > 190 & annual_time_step < 211) %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))

if (i  == 2) {
    
 data$abundance[6] <- 0
 
 data$abundance[18] <- 0
 
 data <-  data %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
 
}

 if(i == 3) {
   
 data$abundance[1:10] <- 0
 
 #data$abundance[18] <- 0
 
 data <-  data %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
   
 }
  
  lims[[i]] <- cbind(min(data$abundance, na.rm = TRUE), 
                     max(data$abundance, na.rm = TRUE))

  plots[[i]] <- ggplot() +
                geom_line(data = data, aes(annual_time_step, abundance)) +
                geom_point(data = data, aes(annual_time_step, abundance,
                                                fill = false_extinction),
                           shape = 21, size = 3) +
  scale_fill_manual(values=c('white', 'red')) +
                plot_theme +
                #coord_cartesian(ylim = c(0,45)) +
                labs(x = "Time",
                     y = "Abundance",
                     title = paste("Replicate", i, sep = " "))+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))

}

abundance_plot <- plot_grid(plots[[1]],
                            plots[[2]],
                            plots[[3]],
                            ncol = 3, align = "v")

abundance_plot

ggsave(file.path(supporting_info_plots_folder, "1_raw_abundance.png"),
       width = 20,
       height = 8,
       units = "cm",
       abundance_plot)

lims1 <- do.call(rbind, lims) 

plotlims <- c(min(lims1[,1], na.rm = TRUE),
          max(lims1[,2], na.rm = TRUE))
        

```
# Plots of raw abundance

```{r weird groups rm plots}

raw_abundance_single <- scenario_ab_gl_formatted[[1]]

raw_plot_inputs <- raw_abundance_single[1:2] 

plots <- list()
lims <- list()

for (i in seq_along(raw_plot_inputs)) {
  
data <- raw_plot_inputs[[i]] %>% 
          filter(group_id == plot_species) %>% 
          arrange(monthly_time_step) %>%                         
          slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
          mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
                 filter(annual_time_step > 0) %>% 
          arrange(monthly_time_step) %>% 
          group_by(annual_time_step) %>% 
          filter(abundance == first(na.omit(abundance))) %>% 
          filter(annual_time_step > 190 & annual_time_step < 211) %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))

if (i  == 2) {
    
 data$abundance[6] <- 0
 
 data$abundance[18] <- 0
 
 data <-  data %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
 
}


  plots[[i]] <- ggplot() +
                geom_line(data = data, aes(annual_time_step, abundance)) +
                geom_point(data = data, aes(annual_time_step, abundance,
                                                fill = false_extinction),
                           shape = 21, size = 3) +
  scale_fill_manual(values=c('white', 'red')) +
                plot_theme +
                #coord_cartesian(ylim = c(0,45)) +
                labs(x = "Time",
                     y = "Abundance",
                     title = paste("Replicate", i, sep = " "))+
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+ 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))

}

abundance_plot2 <- plot_grid(plots[[1]],
                            plots[[2]],
                            ncol = 2, align = "v")

abundance_plot2

ggsave(file.path(supporting_info_plots_folder, "1_weird_groups_rm.png"),
       width = 14,
       height = 8,
       units = "cm",
       abundance_plot2)

```
# Plots of truncated and decomposed time series

```{r decomposed plots}

decomposed_single <- scenario_decomposed[[1]]

decomposed_plot_inputs <- decomposed_single[1:2] 

plots <- list()

for (i in seq_along(decomposed_plot_inputs)) {
  
#   if (i == 4) {
#   
# decomposed <- decomposed_plot_inputs[[i]] %>% 
#           filter(group_id == plot_species) %>% 
#           arrange(monthly_time_step) %>%                         
#           slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
#           mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
#                  filter(annual_time_step > 0) %>% 
#           arrange(monthly_time_step) %>% 
#           group_by(annual_time_step) %>% 
#           filter(abundance == first(na.omit(abundance))) %>% 
#           filter(annual_time_step > 190 & annual_time_step < 211)
# 
# decomposed$abundance[6] <- 0
# 
# decomposed$abundance[18] <- 0
# 
# decomposed <- decomposed %>% 
#             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
# 
#   } else {
  
  decomposed <- decomposed_plot_inputs[[i]] %>% 
          filter(group_id == plot_species) %>% 
          arrange(monthly_time_step) %>%                         
          slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
          mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
                 filter(annual_time_step > 0) %>% 
          arrange(monthly_time_step) %>% 
          group_by(annual_time_step) %>% 
          filter(abundance == first(na.omit(abundance))) %>% 
          filter(annual_time_step > 190 & annual_time_step < 211) %>% 
             mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))
  
#  }
 
   plots[[i]] <- ggplot() +
                geom_line(data = decomposed, aes(annual_time_step, abundance)) +
                geom_point(data = decomposed, aes(annual_time_step, abundance,
                                                fill = false_extinction),
                           shape = 21, size = 3) +
  scale_fill_manual(values=c('white', 'red')) +
                plot_theme +
                coord_cartesian(ylim = plotlims) +
     labs(x = "Time",
                     y = "Abundance",
                     title = paste("Replicate", i, sep = " ")) +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))

}

decomposed_plot <- plot_grid(plots[[1]],
                            plots[[2]],
                            ncol = 2, align = "v")

ggsave(file.path(supporting_info_plots_folder, "2_decomposed.png"),
       width = 14,
       height = 8,
       units = "cm",
       decomposed_plot)

decomposed_plot

```

# Plots of averaged abundance

```{r averaged plot}

averaged <- scenario_averaged[[1]] %>% 
          filter(group_id == plot_species) %>% 
          arrange(monthly_time_step) %>%                         
          slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
          mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
                 filter(annual_time_step > 0) %>% 
          arrange(monthly_time_step) %>% 
          group_by(annual_time_step) %>% 
          filter(abundance == first(na.omit(abundance))) %>% 
          filter(annual_time_step > 190 & annual_time_step < 211) %>% 
            mutate(false_extinction = ifelse(abundance == 0, TRUE, FALSE))

averaged_plot <- ggplot() +
                 geom_line(data = averaged, aes(annual_time_step, abundance)) +
                geom_point(data = averaged, aes(annual_time_step, abundance,
                                                fill = false_extinction),
                           shape = 21, size = 3) +
  scale_fill_manual(values=c('white', 'red')) +
                plot_theme +
                coord_cartesian(ylim = plotlims) +
  labs(x = "Time",
       y = "Abundance",
       title = "Abundance averaged across replicates") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))

averaged_plot

ggsave(file.path(supporting_info_plots_folder, "3_averaged_abundance.png"),
       width = 8,
       height = 8,
       units = "cm",
       averaged_plot)

```
# Plots of smoothed abundance

```{r averaged plot}

smoothed <- scenario_smoothed_abundance[[1]] %>% 
          filter(group_id == plot_species) %>% 
          arrange(monthly_time_step) %>%                         
          slice(1:4800) %>% # Make sure we have exactly 4800 timesteps
          mutate(annual_time_step = rep(-99:300, each = 12)) %>% 
                 filter(annual_time_step > 0) %>% 
          arrange(monthly_time_step) %>% 
          group_by(annual_time_step) %>% 
          filter(abundance == first(na.omit(abundance))) %>% 
          filter(annual_time_step > 190 & annual_time_step < 211)

smoothed_plot <- ggplot() +
                geom_path(data = smoothed, aes(annual_time_step, abundance)) +
                geom_point(data = smoothed, aes(annual_time_step, abundance),
                           shape = 21, fill = "white", size = 3) +
                plot_theme +
                coord_cartesian(ylim = plotlims) +
  labs(x = "Time",
       y = "Abundance",
       title = "Abundance smoothed") +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
    guides(fill=guide_legend(title="Abundance = 0 (false extinction)"))

smoothed_plot

ggsave(file.path(supporting_info_plots_folder, "4_smoothed.png"),
       width = 8,
       height = 8,
       units = "cm",
       smoothed_plot)

```

# Combine plots

```{r combined plots}

all_steps_plot <- plot_grid(abundance_plot,
                            abundance_plot2,
                             decomposed_plot,
                             averaged_plot,
                            smoothed_plot,
                            ncol = 2, align = "v")

all_steps_plot

```

<!-- # RAW vs TRUNCATED (80th percentile) & DECOMPOSED DATA -->
<!-- Using a random replicate and harvested group, show the change in data over -->
<!-- each processing step (number of step represents order in process) -->

<!-- ```{r Raw v Truncated } -->

<!-- # Plot data transformation ---- -->

<!-- ## Get an example group for each scenario (random for baseline, mid size herb for land use, -->
<!-- ## big carn for carnivores, big herb for herbivores) -->
<!-- example_group <- c("10.59", "10.40", "11.68", "10.68") -->

<!-- # Raw abundance -->
<!-- r <- 1 # Pick a replicate -->

<!-- ## * Decomposition ---- -->

<!-- ### Plot the change from raw data to truncated and decomposed -->


<!-- decomposition_plots <- list() -->

<!-- for ( i in seq_along(scenario_ab_gl_formatted)) { -->

<!-- group_raw <- scenario_ab_gl_formatted[[i]][[r]] %>%  -->
<!--              filter(group_id == example_group[[i]]) %>%  -->
<!--              mutate(data_processing_level = "1 - raw for single replicate") -->

<!-- # Decomposed abundance -->

<!-- group_decomposed <- scenario_decomposed[[i]][[r]] %>%  -->
<!--                     filter(group_id == example_group[[i]]) %>%  -->
<!--                     mutate(data_processing_level = "2 - 80th percentile & decomposed for single replicate") -->

<!-- plot_data <- rbind(group_raw, group_decomposed) -->

<!-- decomposition_plots[[i]] <- ggplot(data = plot_data, aes(x = monthly_time_step,  -->
<!--                                                          y = abundance, -->
<!--                                                          col = data_processing_level)) + -->
<!--   geom_point() + -->
<!--   scale_color_manual(values = c("light blue", "pink")) + -->
<!--   theme(panel.grid.major = element_line(linetype = "blank"),  -->
<!--         panel.grid.minor = element_line(linetype = "blank"),  -->
<!--         panel.background = element_rect(fill = "gray49"), -->
<!--         axis.text.y=element_blank(), -->
<!--         axis.ticks.y=element_blank(), -->
<!--         legend.position = "bottom") + -->
<!--   labs(title = scenarios[[i]]) -->

<!-- rm(group_raw, group_decomposed, plot_data) -->

<!-- } -->

<!-- decomposition_plots[[1]] -->
<!-- decomposition_plots[[2]] -->
<!-- decomposition_plots[[3]] -->
<!-- decomposition_plots[[4]] -->

<!-- ``` -->

<!-- # SMOOTHED VS UNSMOOTHED DATA  -->

<!-- Averaged across replicates, for a harvested group -->

<!-- ```{r RLI smoothed v unsmoothed } -->

<!-- smoothing_plots <- list() -->

<!-- for ( i in seq_along(scenario_averaged)) { -->

<!--   group_decomposed <- scenario_decomposed[[i]][[r]] %>%  -->
<!--     filter(group_id == example_group[[i]]) %>%  -->
<!--     mutate(data_processing_level = "2 - 80th percentile & decomposed for one replicate") -->

<!--   # Compare to averaged (not smoothed) -->
<!--   group_averaged <- scenario_averaged[[i]] %>%  -->
<!--     filter(group_id == example_group[[i]]) %>%  -->
<!--     mutate(data_processing_level = "3 - Averaged across replicates") -->

<!--   # Compare to averaged and false extinctions gone -->
<!--   group_smoothed <- scenario_smoothed_abundance[[i]] %>%  -->
<!--     filter(group_id == example_group[[i]]) %>%  -->
<!--     mutate(data_processing_level = "4 - Smoothed over five year rollin window") %>%  -->
<!--     dplyr::select(-abundance) %>%  -->
<!--     rename(abundance = ave_abundance) -->

<!--   plot_data <- rbind(group_decomposed, group_averaged, group_smoothed) -->

<!--   smoothing_plots[[i]] <-  ggplot() + -->
<!--     geom_point(data = plot_data, aes(x = monthly_time_step,  -->
<!--                                      y = abundance, -->
<!--                                      col = data_processing_level), -->
<!--                alpha = 0.2) + -->
<!--     scale_color_manual(values = c("light blue", "purple", "yellow")) + -->
<!--     theme(panel.grid.major = element_line(linetype = "blank"),  -->
<!--           panel.grid.minor = element_line(linetype = "blank"),  -->
<!--           panel.background = element_rect(fill = "gray49"), -->
<!--           axis.text.y=element_blank(), -->
<!--           axis.ticks.y=element_blank(), -->
<!--           legend.position = "bottom") + -->
<!--     labs(title = scenarios[[i]]) -->


<!--   rm(group_smoothed, group_averaged, plot_data, group_decomposed) -->

<!-- } -->

<!-- smoothing_plots[[1]] -->
<!-- smoothing_plots[[2]] -->
<!-- smoothing_plots[[3]] -->
<!-- smoothing_plots[[4]] -->

<!-- ``` -->

<!-- # RED LIST INDEX ANNUAL V1 -->

<!-- Calculating RLI for the functional groups, then taking the mean for each timestep -->
<!-- to get the overall all-species RLI -->

<!-- ## Red List Status Plots -->

<!-- ```{r RLI annual } -->

<!-- # * Create folders ---- -->

<!-- rli_inputs_folder <- file.path(indicator_inputs_folder, "RLI_inputs", today) -->

<!-- if( !dir.exists( file.path(rli_inputs_folder) ) ) { -->
<!--   dir.create( file.path(rli_inputs_folder), recursive = TRUE ) -->

<!-- } -->

<!-- rli_outputs_folder <- file.path(indicator_outputs_folder, "RLI_outputs", today) -->

<!-- if( !dir.exists( file.path(rli_outputs_folder) ) ) { -->
<!--   dir.create( file.path(rli_outputs_folder), recursive = TRUE ) -->

<!-- } -->

<!-- rli_plots_folder <- file.path(indicator_plots_folder, "RLI_plots", today) -->

<!-- if( !dir.exists( file.path(rli_plots_folder) ) ) { -->
<!--   dir.create( file.path(rli_plots_folder), recursive = TRUE ) -->

<!-- } -->

<!-- # * Take an annual sample ---- -->

<!-- interval <- 12 -->

<!-- scenario_annual <- list() -->

<!-- # for (i in seq_along(scenario_averaged)) { -->

<!-- # scenario_groups <- split(scenario_averaged[[i]],  -->
<!-- #                          scenario_averaged[[i]]$group_id) -->

<!-- for (i in seq_along(scenario_smoothed_abundance)) { -->

<!--  scenario_groups <- split(scenario_smoothed_abundance[[i]], -->
<!--                           scenario_smoothed_abundance[[i]]$group_id) -->


<!--   groups_annual <- list() -->


<!--   for (j in seq_along(scenario_groups)) { -->

<!--     # groups_annual[[j]] <- scenario_groups[[j]] %>%  -->
<!--     #   slice(-n()) %>%  -->
<!--     #   slice(which(row_number() %% interval == 0))   -->

<!--      groups_annual[[j]] <- scenario_groups[[j]] %>%  -->
<!--                            group_by(annual_time_step) %>%  -->
<!--      filter(ave_abundance == first(na.omit(ave_abundance))) %>%  -->
<!--        dplyr::select(-monthly_time_step, - true_extinction, -->
<!--                      -abundance, -sd, - error, -lower_ci, -upper_ci) %>%  -->
<!--        distinct(.) %>%  -->
<!--        ungroup(.) %>%  -->
<!--        group_by(group_id, annual_time_step) %>%  -->
<!--        slice(1) %>%  -->
<!--        ungroup(.) -->

<!--     } -->

<!--   groups_annual_df <- do.call(rbind, groups_annual) -->

<!--   scenario_annual[[i]] <- groups_annual_df -->

<!--   rm(groups_annual, groups_annual_df) -->

<!-- } -->

<!-- # * Assign Red List Categories ---- -->

<!-- scenario_red_list_data <- list() -->

<!-- #for (i in seq_along(scenario_ab_gl_formatted)) { -->
<!-- for (i in seq_along(scenario_annual)) { -->

<!--   # Get replicate data for a single scenario -->

<!--   print(paste("Processing scenario", scenarios[[i]], sep = " ")) -->

<!--   # Split by functional group, because we calculate RLI for different -->
<!--   # functional groups then aggregate later (as per Butchart etal 2010), -->
<!--   # except we are using functional groups as proxies for taxa (eg mammals, birds,  -->
<!--   # reptiles) used in real world RLI calcs -->

<!--   status_inputs <- split(scenario_annual[[i]],  -->
<!--                          scenario_annual[[i]]$group_id) -->

<!--   # Make a list to hold output for each individual massbin-func-group (ie virtual spp) -->

<!--   group_red_list_data <- list() -->

<!--   for (j in seq_along(status_inputs)) { -->

<!--     print(paste("Processing group", names(status_inputs)[[j]], sep = " ")) -->

<!--     group_red_list_data[[j]] <- status_inputs[[j]] %>% -->
<!--       # rename(ave_abundance = abundance) %>%  -->
<!--       group_by(group_id) %>% -->
<!--       arrange(annual_time_step) %>% -->
<!--       # calculate the difference in abundance over 10 yrs or 3 generation lengths -->
<!--       # (specified by 'timeframe' column). Its okay to take the first value of  -->
<!--       # timeframe bc the dataframe is grouped by group_id, and timeframe only changes -->
<!--       # between and not within group_ids -->
<!--       # mutate(diff = (abundance - dplyr::lag(abundance, timeframe[1]))) %>% -->
<!--       mutate(diff = (ave_abundance - dplyr::lag(ave_abundance, 10))) %>% -->
<!--       # Using the formula from p 35 (Complex patterns of decline) Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019  -->
<!--       mutate(decline = 1 - ave_abundance/dplyr::lag(ave_abundance, 10)) %>% -->
<!--       mutate(decline = ifelse(ave_abundance == 0, NA, decline)) %>%  -->
<!--       # calculate the rate of change -->
<!--       # mutate(decline = diff/dplyr::lag(abundance, timeframe[1])) %>%  -->
<!--       # mutate(decline = diff/dplyr::lag(ave_abundance, 10)) %>% -->
<!--       # mutate(prev = dplyr::lag(ave_abundance, 10)) %>%  -->
<!--       # assign red list risk status based on decline  -->
<!--       # Using the thresholds from p 16 Categories A2 - A4 Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019 -->
<!--       mutate(rl_status = ifelse(decline < 0.20, "LC", -->
<!--                          ifelse(decline >= 0.20 & decline < 0.30, "NT",  -->
<!--                          ifelse(decline >= 0.30 & decline < 0.50, "VU", -->
<!--                          ifelse(decline >= 0.50 & decline < 0.80, "EN", -->
<!--                          ifelse(decline >= 0.80, "CR", -->
<!--                          ifelse(is.na(decline), "EX", "TBD"))))))) %>% -->
<!--       arrange(group_id, annual_time_step) %>% -->
<!--       # Replace all non-ex status with ex after first occurrence  -->
<!--       # mutate(extinct = match("EX", rl_status)) %>% -->
<!--       mutate(rl_status = ifelse(ave_abundance == 0, "EX", rl_status), -->
<!--              rl_status = ifelse(is.na(rl_status), lag(rl_status, 1), -->
<!--                                 rl_status)) %>%  -->
<!--       mutate(extinct = ifelse(rl_status == "EX", 1, 0)) %>%  -->
<!--       # mutate(rl_status = with(., ave(rl_status,  -->
<!--       #                                         FUN=maintain_ex_status))) -->
<!--       #mutate(rl_status = rl_status) %>%  -->
<!--       group_by(group_id) -->

<!--   } -->

<!--   scenario_red_list_df <- do.call(rbind, group_red_list_data) -->

<!--   scenario_red_list_data[[i]] <- scenario_red_list_df -->

<!--   # Save the inputs -->

<!--   # saveRDS(scenario_red_list_df, -->
<!--   #         file.path(rli_inputs_folder, -->
<!--   #                   paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                         "RLI_input_data_monthly_smoothing.rds", sep = "_"))) -->
<!--   #  -->
<!--   # write.csv(replicate_red_list_df, -->
<!--   #           file.path(rli_inputs_folder, -->
<!--   #                     paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                           "RLI_input_data_monthly_smoothing.csv", sep = "_"))) -->

<!-- } -->


<!-- # * Take coarser sample ---- -->
<!-- ## Heterotrophs -->

<!-- sample_interval <- 1 # interval between samples in years -->
<!-- sample_max_timestep <- 300/sample_interval -->

<!-- scenario_redlist_data_sampled <- list() -->

<!-- for (i in seq_along(scenario_red_list_data)) { -->

<!--   # Sample -->
<!--    sampled <- scenario_red_list_data[[i]] %>% -->
<!--      group_by(group_id) %>% -->
<!--     slice(which(row_number() %% sample_interval == 0)) -->

<!--   # Remove groups that have no biomass in sampled years or you get weird outputs -->

<!--    scenario_redlist_data_sampled[[i]] <- sampled %>% -->
<!--            #rename(abundance = ave_abundance) %>% -->
<!--            group_by(group_id) %>% -->
<!--            mutate(total_abundance = sum(ave_abundance, na.rm = TRUE), -->
<!--                   exists = ifelse(total_abundance == 0 , FALSE, TRUE)) %>% -->
<!--            filter(exists == TRUE) -->
<!-- } -->

<!-- # * Get proportion extinct ---- -->

<!-- scenario_extinctions <- list() -->
<!-- scenario_rl_status_plots <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled)) { -->

<!--   scenario_extinctions[[i]] <- scenario_redlist_data_sampled[[i]] %>%  -->
<!--           group_by(annual_time_step, rl_status) %>%  -->
<!--           filter(rl_status != is.na(rl_status)) %>%  -->
<!--           summarise(test = n()) -->

<!--   scenario_rl_status_plots[[i]] <- ggplot(scenario_extinctions[[i]],  -->
<!--                                           aes(x = annual_time_step,  -->
<!--                                               y = test,  -->
<!--                                               fill = rl_status)) + -->
<!--     geom_bar(position = "stack", stat = "identity") + -->
<!--     scale_fill_viridis_d() + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]],  -->
<!--   #                                          "red_list_status.png", -->
<!--   #                                                sep = "_")), -->
<!--   #        scenario_rl_status_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_rl_status_plots[[1]] -->
<!-- scenario_rl_status_plots[[2]] -->
<!-- scenario_rl_status_plots[[3]] -->
<!-- scenario_rl_status_plots[[4]] -->

<!-- ``` -->

<!-- ## RLI Plots -->

<!-- Blue points are the relative abundance of the harvested group for that scenario -->

<!-- ```{r RLI annual plots} -->

<!-- # RLI by individual functional groups -->

<!-- scenario_fg_rli_outputs <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled)) { -->

<!--   scenario_fg_rli_outputs[[i]] <- calculate_red_list_index( -->
<!--     scenario_redlist_data_sampled[[i]], numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!-- } -->

<!-- # Mean RLI aggregated across groups -->

<!-- scenario_rli_outputs <- list() -->

<!-- for (i in seq_along(scenario_fg_rli_outputs)) { -->

<!--   if ("ci_lower" %in% names(scenario_fg_rli_outputs[[i]])) { -->

<!--     scenario_rli_outputs[[i]] <- scenario_fg_rli_outputs[[i]] %>% -->
<!--       group_by(annual_time_step) %>% -->
<!--       summarise(indicator_score = mean(indicator_score), -->
<!--                 ci_lower = mean(ci_lower), -->
<!--                 ci_upper = mean(ci_upper)) %>% -->
<!--       mutate(indicator = "RLI", -->
<!--              replicate = j) -->
<!--   } else { -->

<!--     scenario_rli_outputs[[i]] <- scenario_fg_rli_outputs[[i]] %>% -->
<!--       group_by(annual_time_step) %>% -->
<!--       summarise(indicator_score = mean(indicator_score)) %>% -->
<!--       mutate(indicator = "RLI", -->
<!--              replicate = j) -->
<!--   } -->

<!-- } -->



<!-- # * Get the mean abundance of all groups in each time step -->

<!-- scenario_mean_abundance <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled)) { -->

<!--   scenario_mean_abundance[[i]] <- scenario_redlist_data_sampled[[i]] %>%  -->
<!--   ungroup() %>%  -->
<!--   group_by(annual_time_step) %>%  -->
<!--   mutate(mean_group_abundance = mean(ave_abundance, na.rm = TRUE)) %>%  -->
<!--   ungroup() %>%  -->
<!--   dplyr::select(annual_time_step, mean_group_abundance) %>%  -->
<!--   distinct(.) -->

<!--   scenario_mean_abundance[[i]]$standardised_abundance <- range01(scenario_mean_abundance[[i]]$mean_group_abundance)   -->

<!-- } -->



<!-- # * Plot RLI ---- -->

<!-- ## By functional group -->

<!-- scenario_fg_rli_plots <- list() -->

<!-- for (i in seq_along(scenario_fg_rli_outputs)) { -->

<!--   scenario_fg_rli_plots[[i]] <-  plot_red_list_index_by_group( -->
<!--     scenario_fg_rli_outputs[[i]], -->
<!--     impact_start, -->
<!--     impact_end, -->
<!--     ci = FALSE) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]],  -->
<!--   #                                          "RLI_by_functional_group_reps_averaged.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_fg_rli_plots[[i]],  device = "png") -->

<!-- } -->

<!-- # RLI with all functional groups aggregated -->
<!-- # i.e. mean of each 'taxa' RLI as per Butchart et al (2010) 'Indicators of -->
<!-- # recent declines' -->

<!-- scenario_rli_plots <- list() -->

<!-- for (i in seq_along(scenario_rli_outputs)) { -->


<!--   scenario_rli_plots[[i]] <- plot_red_list_index(scenario_rli_outputs[[i]], -->
<!--                                                  impact_start,  -->
<!--                                                  impact_end, -->
<!--                                                  ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--                                 labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]], -->
<!--   #                                          "RLI_aggregated_averaged.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_rli_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_rli_plots[[1]] -->
<!-- scenario_rli_plots[[2]] -->
<!-- scenario_rli_plots[[3]] -->
<!-- scenario_rli_plots[[4]] -->
<!-- ``` -->

<!-- # RED LIST INDEX ANNUAL V2  -->

<!-- Lumping all species together to calculate RLI first up, rather than calculating  -->
<!-- by functional group then taking the mean -->

<!-- ``` {r RLI annual v2} -->

<!-- # * Calculate RLI ---- -->

<!-- # RLI across all groups -->

<!-- scenario_all_rli_outputs <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled)) { -->

<!--   scenario_all_rli_outputs[[i]] <- calculate_red_list_index2( -->
<!--     scenario_redlist_data_sampled[[i]], numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!-- } -->

<!-- # * Plot RLI ---- -->

<!-- # Using V2 -->

<!-- scenario_all_rli_plots <- list() -->

<!-- for (i in seq_along(scenario_all_rli_outputs)) { -->

<!--   scenario_all_rli_plots[[i]] <- plot_red_list_index(scenario_all_rli_outputs[[i]], -->
<!--                                                      impact_start,  -->
<!--                                                      impact_end, -->
<!--                                                      ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]], -->
<!--   #                                          "RLI_aggregated_averaged_annual_v2.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_all_rli_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_all_rli_plots[[1]] -->
<!-- scenario_all_rli_plots[[2]] -->
<!-- scenario_all_rli_plots[[3]] -->
<!-- scenario_all_rli_plots[[4]] -->

<!-- ``` -->

<!-- # RED LIST INDEX ANNUAL V3  -->

<!-- Combining all species as above, but only including species larger than 10kg -->

<!-- ```{r RLI annual v3} -->

<!-- # * Calculate RLI ---- -->

<!-- # RLI with only large species -->

<!-- scenario_large_spp_rli_outputs <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled)) { -->

<!--   large_spp <- scenario_redlist_data_sampled[[i]] %>%  -->
<!--               filter(mass_lower > 10000) -->

<!--   scenario_large_spp_rli_outputs[[i]] <- calculate_red_list_index2( -->
<!--     large_spp, numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!--   rm(large_spp) -->

<!-- } -->

<!-- # * Plot RLI ---- -->

<!-- # Using V2 -->

<!-- scenario_large_spp_rli_plots <- list() -->

<!-- for (i in seq_along(scenario_large_spp_rli_outputs)) { -->

<!--   scenario_large_spp_rli_plots[[i]] <- plot_red_list_index(scenario_large_spp_rli_outputs[[i]], -->
<!--                                                      impact_start,  -->
<!--                                                      impact_end, -->
<!--                                                      ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]], -->
<!--   #                                          "RLI_aggregated_averaged_annual_lgspp_v3.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_large_spp_rli_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_large_spp_rli_plots[[1]] -->
<!-- scenario_large_spp_rli_plots[[2]] -->
<!-- scenario_large_spp_rli_plots[[3]] -->
<!-- scenario_large_spp_rli_plots[[4]] -->
<!-- ``` -->

<!-- # RED LIST INDEX 5 YRS V1 -->

<!-- Using data where the Red List status of each species has already been calculated -->
<!-- using annual data, and sampling the status of each species in the first year -->
<!-- of each five year period.  -->

<!-- Calculated by functional group then averaged to get overall all-species RLI -->

<!-- ## Red List Status Plots -->

<!-- ```{r RLI 5yrs v1} -->

<!-- # * Take coarser sample ---- -->
<!-- ## Heterotrophs -->

<!-- sample_interval <- 5 # interval between samples in years -->
<!-- sample_max_timestep <- 300/sample_interval -->

<!-- scenario_redlist_data_sampled_5yr <- list() -->

<!-- for (i in seq_along(scenario_red_list_data)) { -->

<!--   # Sample -->

<!--   set <- seq(5,295,5) -->

<!--   scenario_redlist_data_sampled_5yr[[i]] <- scenario_red_list_data[[i]] %>%  -->
<!--     group_by(group_id) %>% -->
<!--     #Calculate how many timesteps of data available for that species -->
<!--     mutate(n_timesteps = n()) %>%  -->
<!--     #Add a 5 yr interval column for sampling -->
<!--     mutate(annual_time_step = rep(set, each = sample_interval, -->
<!--                           length.out = n_timesteps[1])) %>%  -->
<!--     # Group by species and interval -->
<!--     group_by(group_id, annual_time_step) %>% -->
<!--     # Take the first observation -->
<!--     slice(1) -->

<!--   # Remove groups that have no biomass in sampled years or you get weird outputs -->

<!--   # scenario_redlist_data_sampled_5yr[[i]] <- sampled %>%  -->
<!--   #   rename(abundance = ave_abundance) %>%  -->
<!--   #   group_by(group_id) %>%  -->
<!--   #   mutate(total_abundance = sum(abundance, na.rm = TRUE), -->
<!--   #          exists = ifelse(total_abundance == 0 , FALSE, TRUE)) %>%  -->
<!--   #   filter(exists == TRUE) -->

<!-- } -->



<!-- # * Get proportion extinct ---- -->

<!-- test2 <- scenario_redlist_data_sampled[[1]] %>%  -->
<!--          group_by(annual_time_step) %>%  -->
<!--          summarise(x = n()) -->

<!-- test <- scenario_redlist_data_sampled_5yr[[1]] %>%  -->
<!--         group_by(annual_time_step) %>%  -->
<!--         summarise(x = n()) -->


<!-- scenario_extinctions_5yr <- list() -->
<!-- scenario_rl_status_plots_5yr <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled_5yr)) { -->

<!--   scenario_extinctions_5yr[[i]] <- scenario_redlist_data_sampled_5yr[[i]] %>%  -->
<!--     group_by(annual_time_step, rl_status) %>%  -->
<!--     filter(rl_status != is.na(rl_status)) %>%  -->
<!--     summarise(test = n()) -->

<!--   scenario_rl_status_plots_5yr[[i]] <- ggplot(scenario_extinctions_5yr[[i]],  -->
<!--                                           aes(x = annual_time_step,  -->
<!--                                               y = test,  -->
<!--                                               fill = rl_status)) + -->
<!--     geom_bar(position = "stack", stat = "identity") + -->
<!--     scale_fill_viridis_d() + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]],  -->
<!--   #                                          "red_list_status.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_rl_status_plots_5yr[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_rl_status_plots_5yr[[1]] -->
<!-- scenario_rl_status_plots_5yr[[2]] -->
<!-- scenario_rl_status_plots_5yr[[3]] -->
<!-- scenario_rl_status_plots_5yr[[4]] -->

<!-- ``` -->

<!-- ## RLI Plots -->

<!-- ```{r RLI 5yrs v1 index plots} -->
<!-- # RLI by individual functional groups -->

<!-- scenario_fg_rli_outputs_5yr <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled_5yr)) { -->

<!--   scenario_fg_rli_outputs_5yr[[i]] <- calculate_red_list_index( -->
<!--     scenario_redlist_data_sampled_5yr[[i]], numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!-- } -->

<!-- # Mean RLI aggregated across groups -->

<!-- scenario_rli_outputs_5yr <- list() -->

<!-- for (i in seq_along(scenario_fg_rli_outputs_5yr)) { -->

<!--   if ("ci_lower" %in% names(scenario_fg_rli_outputs_5yr[[i]])) { -->

<!--     scenario_rli_outputs_5yr[[i]] <- scenario_fg_rli_outputs_5yr[[i]] %>% -->
<!--       group_by(annual_time_step) %>% -->
<!--       summarise(indicator_score = mean(indicator_score), -->
<!--                 ci_lower = mean(ci_lower), -->
<!--                 ci_upper = mean(ci_upper)) %>% -->
<!--       mutate(indicator = "RLI", -->
<!--              replicate = j) -->
<!--   } else { -->

<!--     scenario_rli_outputs_5yr[[i]] <- scenario_fg_rli_outputs_5yr[[i]] %>% -->
<!--       group_by(annual_time_step) %>% -->
<!--       summarise(indicator_score = mean(indicator_score)) %>% -->
<!--       mutate(indicator = "RLI", -->
<!--              replicate = j) -->
<!--   } -->

<!-- } -->

<!-- # * Plot RLI ---- -->

<!-- ## By functional group -->

<!-- scenario_rli_plots_fg_5yr <- list() -->

<!-- for (i in seq_along(scenario_fg_rli_outputs_5yr)) { -->

<!--   scenario_rli_plots_fg_5yr[[i]] <-  plot_red_list_index_by_group( -->
<!--     scenario_fg_rli_outputs_5yr[[i]], -->
<!--     impact_start, -->
<!--     impact_end, -->
<!--     ci = FALSE) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]],  -->
<!--   #                                          "RLI_by_functional_group_reps_averaged_5yr.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_rli_outputs_5yr[[i]],  device = "png") -->

<!-- } -->

<!-- # scenario_rli_plots_fg_5yr[[1]] -->
<!-- # scenario_rli_plots_fg_5yr[[2]] -->
<!-- # scenario_rli_plots_fg_5yr[[3]] -->
<!-- # scenario_rli_plots_fg_5yr[[4]] -->
<!-- ``` -->

<!-- ```{r RLI 5 yrs V1 status plots} -->

<!-- scenario_rli_plots_5yr <- list() -->

<!-- for (i in seq_along(scenario_rli_outputs_5yr)) { -->


<!--   scenario_rli_plots_5yr[[i]] <- plot_red_list_index(scenario_rli_outputs_5yr[[i]], -->
<!--                                                  impact_start,  -->
<!--                                                  impact_end, -->
<!--                                                  ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]],  -->
<!--   #                                          "RLI_aggregated_averaged_5yr.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_rli_plots_5yr[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_rli_plots_5yr[[1]] -->
<!-- scenario_rli_plots_5yr[[2]] -->
<!-- scenario_rli_plots_5yr[[3]] -->
<!-- scenario_rli_plots_5yr[[4]] -->
<!-- ``` -->

<!-- # RED LIST INDEX 5 YRS V2  -->

<!-- Assign the red list categories after sampling instead of before. RLI calculated -->
<!-- from all species not via functional groups. -->

<!-- ## Red List Status Plots -->

<!-- ```{r RLI 5yrs v2 status plots} -->

<!-- ## Referring to the thresholds quote under Criterion A, Reason 1 (declines -->
<!-- ## are the result of reversible pressures) according to: -->
<!-- ## https://portals.iucn.org/library/sites/library/files/documents/RL-2001-001-2nd.pdf -->


<!-- # * Assign Red List Categories ---- -->

<!-- scenario_red_list_data_v2 <- list() -->

<!-- #for (i in seq_along(scenario_ab_gl_formatted)) { -->
<!-- for (i in seq_along(scenario_redlist_data_sampled_5yr)) { -->

<!--   # Get replicate data for a single scenario -->

<!--   print(paste("Processing scenario", scenarios[[i]], sep = " ")) -->

<!--   # Split by functional group, because we calculate RLI for different -->
<!--   # functional groups then aggregate later (as per Butchart etal 2010), -->
<!--   # except we are using functional groups as proxies for taxa (eg mammals, birds,  -->
<!--   # reptiles) used in real world RLI calcs -->

<!--   status_inputs <- split(scenario_redlist_data_sampled_5yr[[i]],  -->
<!--                          scenario_redlist_data_sampled_5yr[[i]]$group_id) -->

<!--   # Make a list to hold output for each individual massbin-func-group (ie virtual spp) -->

<!--   group_red_list_data <- list() -->

<!--   for (j in seq_along(status_inputs)) { -->

<!--     print(paste("Processing group", names(status_inputs)[[j]], sep = " ")) -->

<!--     group_red_list_data[[j]] <- status_inputs[[j]] %>% -->
<!--       #rename(ave_abundance = abundance) %>%  -->
<!--       group_by(group_id) %>% -->
<!--       arrange(annual_time_step) %>% -->
<!--       # calculate the difference in abundance over 10 yrs or 3 generation lengths -->
<!--       # (specified by 'timeframe' column). Its okay to take the first value of  -->
<!--       # timeframe bc the dataframe is grouped by group_id, and timeframe only changes -->
<!--       # between and not within group_ids -->
<!--       # mutate(diff = (abundance - dplyr::lag(abundance, timeframe[1]))) %>% -->
<!--       mutate(diff = (ave_abundance - dplyr::lag(ave_abundance, 2))) %>% -->
<!--       # Using the formula from p 35 (Complex patterns of decline) Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019  -->
<!--       mutate(decline = 1 - ave_abundance/dplyr::lag(ave_abundance, 2)) %>% -->
<!--       mutate(decline = ifelse(ave_abundance == 0, NA, decline)) %>%  -->
<!--       # calculate the rate of change -->
<!--       # mutate(decline = diff/dplyr::lag(abundance, timeframe[1])) %>%  -->
<!--       # mutate(decline = diff/dplyr::lag(ave_abundance, 10)) %>% -->
<!--       # mutate(prev = dplyr::lag(ave_abundance, 10)) %>%  -->
<!--       # assign red list risk status based on decline  -->
<!--       # Using the thresholds from p 16 Categories A2 - A4 Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019 -->
<!--       mutate(rl_status = ifelse(decline < 0.20, "LC", -->
<!--                                 ifelse(decline >= 0.20 & decline < 0.30, "NT",  -->
<!--                                        ifelse(decline >= 0.30 & decline < 0.50, "VU", -->
<!--                                               ifelse(decline >= 0.50 & decline < 0.80, "EN", -->
<!--                                                      ifelse(decline >= 0.80, "CR", -->
<!--                                                             ifelse(is.na(decline), "EX", "TBD"))))))) %>% -->
<!--       arrange(group_id, annual_time_step) %>% -->
<!--       # Replace all non-ex status with ex after first occurrence  -->
<!--       # mutate(extinct = match("EX", rl_status)) %>% -->
<!--       mutate(rl_status = ifelse(ave_abundance == 0, "EX", rl_status)) %>%  -->
<!--       mutate(extinct = ifelse(rl_status == "EX", 1, 0)) %>%  -->
<!--       # mutate(rl_status = with(., ave(rl_status,  -->
<!--       #                                         FUN=maintain_ex_status))) -->
<!--       #mutate(rl_status = rl_status) %>%  -->
<!--       group_by(group_id) -->

<!--   } -->

<!--   scenario_red_list_df <- do.call(rbind, group_red_list_data) -->

<!--   scenario_red_list_data_v2[[i]] <- scenario_red_list_df -->

<!--   rm(scenario_red_list_df, group_red_list_data, status_inputs) -->

<!--   # Save the inputs -->

<!--   # saveRDS(scenario_red_list_df, -->
<!--   #         file.path(rli_inputs_folder, -->
<!--   #                   paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                         "RLI_input_data_monthly_smoothing.rds", sep = "_"))) -->
<!--   #  -->
<!--   # write.csv(replicate_red_list_df, -->
<!--   #           file.path(rli_inputs_folder, -->
<!--   #                     paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                           "RLI_input_data_monthly_smoothing.csv", sep = "_"))) -->

<!-- } -->


<!-- # Have a quick look at the outputs -->

<!-- # * Get proportion extinct ---- -->

<!-- scenario_extinctions <- list() -->
<!-- scenario_rl_status_plots <- list() -->

<!-- for (i in seq_along(scenario_red_list_data_v2)) { -->

<!--   scenario_extinctions[[i]] <- scenario_red_list_data_v2[[i]] %>%  -->
<!--     group_by(annual_time_step, rl_status) %>%  -->
<!--     filter(rl_status != is.na(rl_status)) %>%  -->
<!--     summarise(test = n()) -->

<!--   scenario_rl_status_plots[[i]] <- ggplot(scenario_extinctions[[i]],  -->
<!--                                           aes(x = annual_time_step,  -->
<!--                                               y = test,  -->
<!--                                               fill = rl_status)) + -->
<!--     geom_bar(position = "stack", stat = "identity") + -->
<!--     scale_fill_viridis_d() + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]],  -->
<!--   #                                          "red_list_status.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_rl_status_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_rl_status_plots[[1]] -->
<!-- scenario_rl_status_plots[[2]] -->
<!-- scenario_rl_status_plots[[3]] -->
<!-- scenario_rl_status_plots[[4]] -->

<!-- ``` -->

<!-- ## RLI Plots  -->

<!-- ```{r RLI 5yr plots v2} -->

<!-- # RLI by individual functional groups -->

<!-- # scenario_fg_rli_outputs_v2 <- list() -->
<!-- #  -->
<!-- # for (i in seq_along(scenario_red_list_data_v2)) { -->
<!-- #    -->
<!-- #   scenario_fg_rli_outputs_v2[[i]] <- calculate_red_list_index( -->
<!-- #     scenario_red_list_data_v2[[i]], numboots, ci = FALSE) %>% -->
<!-- #     mutate(scenario = scenarios[[i]])  -->
<!-- #    -->
<!-- # } -->

<!-- # RLI across all groups -->

<!-- scenario_all_rli_outputs_v2 <- list() -->

<!-- for (i in seq_along(scenario_red_list_data_v2)) { -->

<!--   scenario_all_rli_outputs_v2[[i]] <- calculate_red_list_index2( -->
<!--     scenario_red_list_data_v2[[i]], numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!-- } -->

<!-- # * Plot RLI ---- -->

<!-- # Using V2 -->

<!-- scenario_all_rli_plots_v2 <- list() -->

<!-- for (i in seq_along(scenario_all_rli_outputs_v2)) { -->

<!--   scenario_all_rli_plots_v2[[i]] <- plot_red_list_index(scenario_all_rli_outputs_v2[[i]], -->
<!--                                                  impact_start,  -->
<!--                                                  impact_end, -->
<!--                                                  ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]], -->
<!--   #                                          "RLI_aggregated_averaged_5yr2.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_all_rli_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_all_rli_plots_v2[[1]] -->
<!-- scenario_all_rli_plots_v2[[2]] -->
<!-- scenario_all_rli_plots_v2[[3]] -->
<!-- scenario_all_rli_plots_v2[[4]] -->

<!-- ``` -->

<!-- # RED LIST INDEX 5YRS V3  -->

<!-- RLI same as above, but with only large species (>10kg) -->

<!-- ```{r RLI 5yrs v3 } -->

<!-- scenario_large_spp_rli_outputs_5yr <- list() -->

<!-- for (i in seq_along(scenario_redlist_data_sampled_5yr)) { -->

<!--   large_spp <- scenario_redlist_data_sampled_5yr[[i]] %>%  -->
<!--     tidylog::filter(mass_lower > 10000) -->

<!--   scenario_large_spp_rli_outputs_5yr[[i]] <- calculate_red_list_index2( -->
<!--     large_spp, numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!--   rm(large_spp) -->

<!-- } -->

<!-- # * Plot RLI ---- -->

<!-- # Using V2 -->

<!-- scenario_large_spp_rli_plots_5yr <- list() -->

<!-- for (i in seq_along(scenario_large_spp_rli_outputs)) { -->

<!--   scenario_large_spp_rli_plots_5yr[[i]] <- plot_red_list_index(scenario_large_spp_rli_outputs_5yr[[i]], -->
<!--                                                            impact_start,  -->
<!--                                                            impact_end, -->
<!--                                                            ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]], -->
<!--   #                                          "RLI_aggregated_averaged_5yr_lgspp_v3.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_large_spp_rli_plots_5yr[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_large_spp_rli_plots_5yr[[1]] -->
<!-- scenario_large_spp_rli_plots_5yr[[2]] -->
<!-- scenario_large_spp_rli_plots_5yr[[3]] -->
<!-- scenario_large_spp_rli_plots_5yr[[4]] -->

<!-- ``` -->

<!-- # RED LIST INDEX 5 YRS V4 -->

<!-- The same as V2, but with only 5 replicates to see if more reps = smoother outputs -->

<!-- ```{r Sample using only 5 reps} -->


<!-- # * Take an annual sample ---- -->

<!-- interval <- 12 -->

<!-- scenario_annual_5_reps <- list() -->

<!-- # for (i in seq_along(scenario_averaged)) { -->

<!-- # scenario_groups <- split(scenario_averaged[[i]],  -->
<!-- #                          scenario_averaged[[i]]$group_id) -->

<!-- for (i in seq_along(scenario_smoothed_5_reps)) { -->

<!--  scenario_groups <- split(scenario_smoothed_5_reps[[i]], -->
<!--                           scenario_smoothed_5_reps[[i]]$group_id) -->


<!--   groups_annual <- list() -->


<!--   for (j in seq_along(scenario_groups)) { -->

<!--     # groups_annual[[j]] <- scenario_groups[[j]] %>%  -->
<!--     #   slice(-n()) %>%  -->
<!--     #   slice(which(row_number() %% interval == 0))   -->

<!--      groups_annual[[j]] <- scenario_groups[[j]] %>%  -->
<!--                            group_by(annual_time_step) %>%  -->
<!--      filter(ave_abundance == first(na.omit(ave_abundance))) %>%  -->
<!--        dplyr::select(-monthly_time_step, - true_extinction, -->
<!--                      -abundance, -sd, - error, -lower_ci, -upper_ci) %>%  -->
<!--        distinct(.) %>%  -->
<!--        ungroup(.) %>%  -->
<!--        group_by(group_id, annual_time_step) %>%  -->
<!--        slice(1) %>%  -->
<!--        ungroup(.) -->

<!--     } -->

<!--   groups_annual_df <- do.call(rbind, groups_annual) -->

<!--   scenario_annual_5_reps[[i]] <- groups_annual_df -->

<!--   rm(groups_annual, groups_annual_df) -->

<!-- } -->

<!-- # * Assign Red List Categories ---- -->

<!-- scenario_red_list_data_5_reps <- list() -->

<!-- #for (i in seq_along(scenario_ab_gl_formatted)) { -->
<!-- for (i in seq_along(scenario_annual_5_reps)) { -->

<!--   # Get replicate data for a single scenario -->

<!--   #print(paste("Processing scenario", scenarios[[i]], sep = " ")) -->

<!--   # Split by functional group, because we calculate RLI for different -->
<!--   # functional groups then aggregate later (as per Butchart etal 2010), -->
<!--   # except we are using functional groups as proxies for taxa (eg mammals, birds,  -->
<!--   # reptiles) used in real world RLI calcs -->

<!--   status_inputs <- split(scenario_annual_5_reps[[i]],  -->
<!--                          scenario_annual_5_reps[[i]]$group_id) -->

<!--   # Make a list to hold output for each individual massbin-func-group (ie virtual spp) -->

<!--   group_red_list_data <- list() -->

<!--   for (j in seq_along(status_inputs)) { -->

<!--     #print(paste("Processing group", names(status_inputs)[[j]], sep = " ")) -->

<!--     group_red_list_data[[j]] <- status_inputs[[j]] %>% -->
<!--       # rename(ave_abundance = abundance) %>%  -->
<!--       group_by(group_id) %>% -->
<!--       arrange(annual_time_step) %>% -->
<!--       # calculate the difference in abundance over 10 yrs or 3 generation lengths -->
<!--       # (specified by 'timeframe' column). Its okay to take the first value of  -->
<!--       # timeframe bc the dataframe is grouped by group_id, and timeframe only changes -->
<!--       # between and not within group_ids -->
<!--       # mutate(diff = (abundance - dplyr::lag(abundance, timeframe[1]))) %>% -->
<!--       mutate(diff = (ave_abundance - dplyr::lag(ave_abundance, 10))) %>% -->
<!--       # Using the formula from p 35 (Complex patterns of decline) Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019  -->
<!--       mutate(decline = 1 - ave_abundance/dplyr::lag(ave_abundance, 10)) %>% -->
<!--       mutate(decline = ifelse(ave_abundance == 0, NA, decline)) %>%  -->
<!--       # calculate the rate of change -->
<!--       # mutate(decline = diff/dplyr::lag(abundance, timeframe[1])) %>%  -->
<!--       # mutate(decline = diff/dplyr::lag(ave_abundance, 10)) %>% -->
<!--       # mutate(prev = dplyr::lag(ave_abundance, 10)) %>%  -->
<!--       # assign red list risk status based on decline  -->
<!--       # Using the thresholds from p 16 Categories A2 - A4 Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019 -->
<!--       mutate(rl_status = ifelse(decline < 0.20, "LC", -->
<!--                          ifelse(decline >= 0.20 & decline < 0.30, "NT",  -->
<!--                          ifelse(decline >= 0.30 & decline < 0.50, "VU", -->
<!--                          ifelse(decline >= 0.50 & decline < 0.80, "EN", -->
<!--                          ifelse(decline >= 0.80, "CR", -->
<!--                          ifelse(is.na(decline), "EX", "TBD"))))))) %>% -->
<!--       arrange(group_id, annual_time_step) %>% -->
<!--       # Replace all non-ex status with ex after first occurrence  -->
<!--       # mutate(extinct = match("EX", rl_status)) %>% -->
<!--       mutate(rl_status = ifelse(ave_abundance == 0, "EX", rl_status), -->
<!--              rl_status = ifelse(is.na(rl_status), lag(rl_status, 1), -->
<!--                                 rl_status)) %>%  -->
<!--       mutate(extinct = ifelse(rl_status == "EX", 1, 0)) %>%  -->
<!--       # mutate(rl_status = with(., ave(rl_status,  -->
<!--       #                                         FUN=maintain_ex_status))) -->
<!--       #mutate(rl_status = rl_status) %>%  -->
<!--       group_by(group_id) -->

<!--   } -->

<!--   scenario_red_list_df <- do.call(rbind, group_red_list_data) -->

<!--   scenario_red_list_data_5_reps[[i]] <- scenario_red_list_df -->

<!--   # Save the inputs -->

<!--   # saveRDS(scenario_red_list_df, -->
<!--   #         file.path(rli_inputs_folder, -->
<!--   #                   paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                         "RLI_input_data_monthly_smoothing.rds", sep = "_"))) -->
<!--   #  -->
<!--   # write.csv(replicate_red_list_df, -->
<!--   #           file.path(rli_inputs_folder, -->
<!--   #                     paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                           "RLI_input_data_monthly_smoothing.csv", sep = "_"))) -->

<!-- } -->



<!-- # * Take coarser sample ---- -->
<!-- ## Heterotrophs -->

<!-- sample_interval <- 5 # interval between samples in years -->
<!-- sample_max_timestep <- 300/sample_interval -->

<!-- scenario_redlist_data_sampled_5yr_5_reps <- list() -->

<!-- for (i in seq_along(scenario_red_list_data_5_reps)) { -->

<!--   # Sample -->

<!--   set <- seq(5,295,5) -->

<!--   scenario_redlist_data_sampled_5yr_5_reps[[i]] <- scenario_red_list_data_5_reps[[i]] %>%  -->
<!--     group_by(group_id) %>% -->
<!--     #Calculate how many timesteps of data available for that species -->
<!--     mutate(n_timesteps = n()) %>%  -->
<!--     #Add a 5 yr interval column for sampling -->
<!--     mutate(annual_time_step = rep(set, each = sample_interval, -->
<!--                           length.out = n_timesteps[1])) %>%  -->
<!--     # Group by species and interval -->
<!--     group_by(group_id, annual_time_step) %>% -->
<!--     # Take the first observation -->
<!--     slice(1) -->

<!--   # Remove groups that have no biomass in sampled years or you get weird outputs -->

<!--   # scenario_redlist_data_sampled_5yr[[i]] <- sampled %>%  -->
<!--   #   rename(abundance = ave_abundance) %>%  -->
<!--   #   group_by(group_id) %>%  -->
<!--   #   mutate(total_abundance = sum(abundance, na.rm = TRUE), -->
<!--   #          exists = ifelse(total_abundance == 0 , FALSE, TRUE)) %>%  -->
<!--   #   filter(exists == TRUE) -->

<!-- } -->

<!-- ## Referring to the thresholds quote under Criterion A, Reason 1 (declines -->
<!-- ## are the result of reversible pressures) according to: -->
<!-- ## https://portals.iucn.org/library/sites/library/files/documents/RL-2001-001-2nd.pdf -->


<!-- # * Assign Red List Categories ---- -->

<!-- scenario_red_list_data_v2_5_reps <- list() -->

<!-- #for (i in seq_along(scenario_ab_gl_formatted)) { -->
<!-- for (i in seq_along(scenario_redlist_data_sampled_5yr_5_reps)) { -->

<!--   # Get replicate data for a single scenario -->

<!--  # print(paste("Processing scenario", scenarios[[i]], sep = " ")) -->

<!--   # Split by functional group, because we calculate RLI for different -->
<!--   # functional groups then aggregate later (as per Butchart etal 2010), -->
<!--   # except we are using functional groups as proxies for taxa (eg mammals, birds,  -->
<!--   # reptiles) used in real world RLI calcs -->

<!--   status_inputs <- split(scenario_redlist_data_sampled_5yr_5_reps[[i]],  -->
<!--                          scenario_redlist_data_sampled_5yr_5_reps[[i]]$group_id) -->

<!--   # Make a list to hold output for each individual massbin-func-group (ie virtual spp) -->

<!--   group_red_list_data <- list() -->

<!--   for (j in seq_along(status_inputs)) { -->

<!--     #print(paste("Processing group", names(status_inputs)[[j]], sep = " ")) -->

<!--     group_red_list_data[[j]] <- status_inputs[[j]] %>% -->
<!--       #rename(ave_abundance = abundance) %>%  -->
<!--       group_by(group_id) %>% -->
<!--       arrange(annual_time_step) %>% -->
<!--       # calculate the difference in abundance over 10 yrs or 3 generation lengths -->
<!--       # (specified by 'timeframe' column). Its okay to take the first value of  -->
<!--       # timeframe bc the dataframe is grouped by group_id, and timeframe only changes -->
<!--       # between and not within group_ids -->
<!--       # mutate(diff = (abundance - dplyr::lag(abundance, timeframe[1]))) %>% -->
<!--       mutate(diff = (ave_abundance - dplyr::lag(ave_abundance, 2))) %>% -->
<!--       # Using the formula from p 35 (Complex patterns of decline) Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019  -->
<!--       mutate(decline = 1 - ave_abundance/dplyr::lag(ave_abundance, 2)) %>% -->
<!--       mutate(decline = ifelse(ave_abundance == 0, NA, decline)) %>%  -->
<!--       # calculate the rate of change -->
<!--       # mutate(decline = diff/dplyr::lag(abundance, timeframe[1])) %>%  -->
<!--       # mutate(decline = diff/dplyr::lag(ave_abundance, 10)) %>% -->
<!--       # mutate(prev = dplyr::lag(ave_abundance, 10)) %>%  -->
<!--       # assign red list risk status based on decline  -->
<!--       # Using the thresholds from p 16 Categories A2 - A4 Guidelines  -->
<!--       # for Using the IUCN Red List Categories and Criteria v14 August 2019 -->
<!--       mutate(rl_status = ifelse(decline < 0.20, "LC", -->
<!--                                 ifelse(decline >= 0.20 & decline < 0.30, "NT",  -->
<!--                                        ifelse(decline >= 0.30 & decline < 0.50, "VU", -->
<!--                                               ifelse(decline >= 0.50 & decline < 0.80, "EN", -->
<!--                                                      ifelse(decline >= 0.80, "CR", -->
<!--                                                             ifelse(is.na(decline), "EX", "TBD"))))))) %>% -->
<!--       arrange(group_id, annual_time_step) %>% -->
<!--       # Replace all non-ex status with ex after first occurrence  -->
<!--       # mutate(extinct = match("EX", rl_status)) %>% -->
<!--       mutate(rl_status = ifelse(ave_abundance == 0, "EX", rl_status)) %>%  -->
<!--       mutate(extinct = ifelse(rl_status == "EX", 1, 0)) %>%  -->
<!--       # mutate(rl_status = with(., ave(rl_status,  -->
<!--       #                                         FUN=maintain_ex_status))) -->
<!--       #mutate(rl_status = rl_status) %>%  -->
<!--       group_by(group_id) -->

<!--   } -->

<!--   scenario_red_list_df <- do.call(rbind, group_red_list_data) -->

<!--   scenario_red_list_data_v2_5_reps[[i]] <- scenario_red_list_df -->

<!--   rm(scenario_red_list_df, group_red_list_data, status_inputs) -->

<!--   # Save the inputs -->

<!--   # saveRDS(scenario_red_list_df, -->
<!--   #         file.path(rli_inputs_folder, -->
<!--   #                   paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                         "RLI_input_data_monthly_smoothing.rds", sep = "_"))) -->
<!--   #  -->
<!--   # write.csv(replicate_red_list_df, -->
<!--   #           file.path(rli_inputs_folder, -->
<!--   #                     paste(today, scenarios[[i]], "replicate", j, -->
<!--   #                           "RLI_input_data_monthly_smoothing.csv", sep = "_"))) -->

<!-- } -->


<!-- ``` -->

<!-- ## RLI Plots  -->

<!-- ```{r RLI 5yr plots v4} -->

<!-- # RLI by individual functional groups -->

<!-- # scenario_fg_rli_outputs_v2 <- list() -->
<!-- #  -->
<!-- # for (i in seq_along(scenario_red_list_data_v2)) { -->
<!-- #    -->
<!-- #   scenario_fg_rli_outputs_v2[[i]] <- calculate_red_list_index( -->
<!-- #     scenario_red_list_data_v2[[i]], numboots, ci = FALSE) %>% -->
<!-- #     mutate(scenario = scenarios[[i]])  -->
<!-- #    -->
<!-- # } -->

<!-- # RLI across all groups -->

<!-- scenario_all_rli_outputs_v2_5_reps <- list() -->

<!-- for (i in seq_along(scenario_red_list_data_v2_5_reps)) { -->

<!--   scenario_all_rli_outputs_v2_5_reps[[i]] <- calculate_red_list_index2( -->
<!--     scenario_red_list_data_v2_5_reps[[i]], numboots, ci = FALSE) %>% -->
<!--     mutate(scenario = scenarios[[i]])  -->

<!-- } -->

<!-- # * Plot RLI ---- -->

<!-- # Using V2 -->

<!-- scenario_all_rli_plots_v2_5_reps <- list() -->

<!-- for (i in seq_along(scenario_all_rli_outputs_v2_5_reps)) { -->

<!--   scenario_all_rli_plots_v2_5_reps[[i]] <- plot_red_list_index(scenario_all_rli_outputs_v2_5_reps[[i]], -->
<!--                                                  impact_start,  -->
<!--                                                  impact_end, -->
<!--                                                  ci = FALSE, -->
<!--                                                  scenario_harvested[[i]]) + -->
<!--     labs(title = scenarios[[i]]) -->

<!--   # ggsave(file.path(rli_plots_folder, paste(today, scenarios[[i]], -->
<!--   #                                          "RLI_aggregated_averaged_5yr2.png", -->
<!--   #                                          sep = "_")), -->
<!--   #        scenario_all_rli_plots[[i]],  device = "png") -->

<!-- } -->

<!-- scenario_all_rli_plots_v2_5_reps[[1]] -->
<!-- scenario_all_rli_plots_v2_5_reps[[2]] -->
<!-- scenario_all_rli_plots_v2_5_reps[[3]] -->
<!-- scenario_all_rli_plots_v2_5_reps[[4]] -->

<!-- ``` -->
